In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_excel("std_data.xlsx")

In [20]:
data

,"⚠️ DIRTY DATA - Mein Missing Values, Duplicates, Spelling Mistakes, Outliers aur Wrong Types hain - Pehle Clean Karen!",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Student_ID,Student_Name,Study_Hours_Per_Day,Attendance_%,Previous_GPA,Assignments_Submitted,Sleep_Hours,Final_Marks
1,STU001,Fatima Noor,4.4,90.4,3.85,1.0,6.1,100
2,STU002,Ali Hassan,9.6,94.8,3.88,2.0,8.5,100
3,STU003,Hamza Sheikh,NaN,65.9,NaN,0.0,4.6,96.5
4,STU004,Zainab Hussain,6.4,55.5,2.43,0.0,NaN,83.8
...,...,...,...,...,...,...,...,...
121,STU054,Faisal Nawaz,9.1,61.3,-1,8.0,4.8,100
122,STU102,Amna Butt,6.7,78.4,NaN,9.0,6.8,100
123,STU021,Usman Ali,NaN,98.1,3.04,9.0,4.2,100
124,STU044,Sara Khan,NaN,NaN,1.73,3.0,NaN,100
125,STU027,Hamza Sheikh,2.8,NaN,3.24,3.0,8.8,92.6

In [21]:
data.columns = data.iloc[0]
data = data[1:]
data.reset_index(drop=True, inplace=True)

In [23]:
cols = ['Study_Hours_Per_Day','Attendance_%','Previous_GPA',
        'Assignments_Submitted','Sleep_Hours','Final_Marks']

for col in cols:
    data.loc[:,col] = pd.to_numeric(data[col], errors='coerce')

In [24]:
data.duplicated().sum()

np.int64(3)

In [27]:
data = data.drop_duplicates()

In [28]:
data = data.fillna(data.mean(numeric_only = True))

In [29]:
data.isna().sum()

0
Student_ID               0
Student_Name             0
Study_Hours_Per_Day      0
Attendance_%             0
Previous_GPA             0
Assignments_Submitted    0
Sleep_Hours              0
Final_Marks              0
dtype: int64

In [4]:
data.head(1)

,"⚠️ DIRTY DATA - Mein Missing Values, Duplicates, Spelling Mistakes, Outliers aur Wrong Types hain - Pehle Clean Karen!",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Student_ID,Student_Name,Study_Hours_Per_Day,Attendance_%,Previous_GPA,Assignments_Submitted,Sleep_Hours,Final_Marks

In [30]:
X = data.drop(columns=['Final_Marks','Student_ID','Student_Name'])
y = data['Final_Marks']

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer( transformers=[('num', StandardScaler(), X.columns)])

In [33]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

pipeline = Pipeline(steps=[('preprocessing', preprocessor),('model', LinearRegression())])

In [152]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.58, random_state=86)

In [153]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['Study_Hours_Per_Day', 'Attendance_%', 'Previous_GPA',
       'Assignments_Submitted', 'Sleep_Hours'],
      dtype='object', name=0))])),
                ('model', LinearRegression())])

In [154]:
y_pred = pipeline.predict(X_test)

In [155]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(r2)

-0.055513815847274994